In [2]:
liste = list(range(1, 11)) 
for nombre in liste:
    print(nombre)

1
2
3
4
5
6
7
8
9
10


In [3]:
def trier_liste(liste):
    return sorted(liste)


In [5]:
ma_liste = [3, 1, 4, 1, 5, 9, 2] 
print(trier_liste(ma_liste))

[1, 1, 2, 3, 4, 5, 9]


In [7]:
def afficher_villes(dictionnaire):
    for ville, pays in dictionnaire.items(): 
        print(f"{ville} est dans {pays}")

villes = {
"Paris": "France", "Berlin": "Allemagne", "Madrid": "Espagne"
} 
afficher_villes(villes)

Paris est dans France
Berlin est dans Allemagne
Madrid est dans Espagne


In [8]:
import numpy as np
matrice = np.array([[1, 2, 3], [4, 5, 6]]) 
print(matrice)

[[1 2 3]
 [4 5 6]]


In [9]:
def somme_matrice(matrice):
    return np.sum(matrice)
matrice = np.array([[1, 2, 3], [4, 5, 6]]) 
print(somme_matrice(matrice))

21


In [10]:
tableau = np.arange(10) 
premiers_elements = tableau[:5] 
print(premiers_elements)

[0 1 2 3 4]


In [11]:
def transposee(matrice):
    return np.transpose(matrice)


In [12]:
matrice = np.array([[1, 2], [3, 4]]) 
print(transposee(matrice))

[[1 3]
 [2 4]]
